[
  {
    titulo: 'Clean Architecture',
    descricao: 'Clean Architecture course for begginers',
    data_inicio: '2023-01-01',
    categoria_id: 1,
    docente_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    titulo: 'SpringBoot',
    descricao: 'Java course with Spring Framework',
    data_inicio: '2023-01-01',
    categoria_id: 2,
    docente_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    titulo: 'Scrum Management',
    descricao: 'Agile Framework for projects',
    data_inicio: '2023-01-01',
    categoria_id: 3,
    docente_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    titulo: 'AWS and Google Cloud',
    descricao: 'Automatized Deploys',
    data_inicio: '2023-01-01',
    categoria_id: 4,
    docente_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
